src/OnlineJewelleryShopping/Models/banner.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineJewelleryShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class banner
    {
        public int banner_id { get; set; }
        public string banner_url { get; set; }
        public string banner_image { get; set; }
    }
}

src/OnlineJewelleryShopping/Areas/Admin/Controllers/BannerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineJewelleryShopping.Models;
using OnlineJewelleryShopping.Areas.Admin.Models;

using PagedList;
namespace OnlineJewelleryShopping.Areas.Admin.Controllers
{
    public class BannerController : Controller
    {
        private OnlineJewelleryStoreEntities db = new OnlineJewelleryStoreEntities();

        //
        // GET: /Admin/Banner/

        public ActionResult Index(int PageNumber = 1, int PageSize = 5)
        {
            //Get all banner
            var lstObj = from b in db.banners orderby b.banner_id select b;
            //Render view with model
            return View(lstObj.ToPagedList(PageNumber, PageSize));
        }

        //
        // GET: /Admin/Banner/Details/5
        [HttpPost]
        public ActionResult Index(FormCollection collection)
        {

            foreach (string item in collection.Keys)
            {
                int id = int.Parse(item);
                db.banners.Remove(db.banners.Find(id));
            }
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        public ActionResult Details(int id = 0)
        {
            //Find in database
            banner banner = db.banners.Find(id);
            if (banner == null) //Not found return error 404
            {
                return HttpNotFound();
            }
            //Found
            //Render View
            return View(banner);
        }

        //
        // GET: /Admin/Banner/Create

        public ActionResult Create()
        {
            //Render Create form
            return View();
        }

        //
        // POST: /Admin/Banner/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BannerModel banner)
        {
            //Check ModelState
            if (ModelState.IsValid)  //Model is valid
            {
                //Add new banner to database 
                db.banners.Add(new banner()
                {
                    banner_image = banner.banner_image,
                    banner_url = banner.banner_url
                });
                //Save
                db.SaveChanges();
                //Redirect to Index action
                return RedirectToAction("Index");
            }
            //Model is invalid
            //Return view and display error message
            return View(banner);
        }

        //
        // GET: /Admin/Banner/Edit/5

        public ActionResult Edit(int id = 0)
        {
            //Find in  dtaabase
            banner banner = db.banners.Find(id);

            //Check result
            if (banner == null) //Not found in database error 404
            {
                return HttpNotFound();
            }
            //Found
            //Render edit form
            return View(new BannerModel()
            {
                banner_id = banner.banner_id,
                banner_image = banner.banner_image,
                banner_url = banner.banner_url
            });
        }

        //
        // POST: /Admin/Banner/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BannerModel banner)
        {
            //Check Model
            if (ModelState.IsValid) //Model is valid
            {
                var ban = new banner();
                ban.banner_id = banner.banner_id;
                ban.banner_image = banner.banner_image;
                ban.banner_url = banner.banner_url;
                db.Entry(ban).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //Model is invalid
            //Return View and display error message
            return View(banner);
        }

        //
        // GET: /Admin/Banner/Delete/5

        public ActionResult Delete(int id = 0)
        {
            //Find in database
            banner banner = db.banners.Find(id);

            //Check result 
            if (banner == null) //Not found return error 404
            {
                return HttpNotFound();
            }
            //Found 
            //Render view delete confirm
            return View(banner);
        }

        //
        // POST: /Admin/Banner/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //Find in database
            banner banner = db.banners.Find(id);
            //Remove
            db.banners.Remove(banner);
            //Save to database
            db.SaveChanges();
            //Redirect to index action
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

src/OnlineJewelleryShopping/Areas/Admin/Views/Banner/Create.cshtml
@model OnlineJewelleryShopping.Areas.Admin.Models.BannerModel

@{
    ViewBag.Title = "Create";
}
@{
    ViewBag.PageHeading = "Create Banner";
    
}
<div id="table-content">
    @using (Html.BeginForm("Create", "Banner", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <table width="100%" id="table-form">
            <tr align="left">
                <th width="100px">Url</th>
                <td>@Html.TextBoxFor(m => m.banner_url, new { id = "banner_url" }) @Html.ValidationMessageFor(m => m.banner_url)</td>
            </tr>
            <tr>
                <th width="100px" align="left">Image</th>
                <td>@Html.TextBoxFor(m => m.banner_image, new { id = "banner_image", @readonly = "readonly" }) <input type="button" name="name" value="Browse Server" onclick="BrowseServerFile('banner_image');" /> @Html.ValidationMessageFor(m => m.banner_image)</td>
            </tr>
            <tr><th colspan="2" align="left"><input type="submit" value="Save" /> @Html.ActionLink("Back to List", "Index")</th></tr>
        </table>
    }
</div>

src/OnlineJewelleryShopping/Areas/Admin/Views/Banner/Delete.cshtml
@model OnlineJewelleryShopping.Models.banner

@{
    ViewBag.Title = "Delete";
}
@{

    ViewBag.PageHeading = "Delete banner";
}
<h3>Are you sure you want to delete this?</h3>
<div id="table-content">
    <table width="100%" id="table-form">
        <tr align="left">
            <th width="100px">Url</th>
            <td>@Html.DisplayFor(model => model.banner_url)</td>
        </tr>
        <tr align="left">
            <th>Image</th>
            <td><img src="@Url.Content(Model.banner_image)" alt="" style="max-width:930px;" /></td>
        </tr>
       
        <tr>
            <th colspan="2">
                @using (Html.BeginForm()) {
                    @Html.AntiForgeryToken()

                    <input type="submit" value="Delete" /> 
        @Html.ActionLink("Back to List", "Index")

}
            </th>
        </tr>
    </table>
</div>

src/OnlineJewelleryShopping/Areas/Admin/Views/Banner/Details.cshtml
@model OnlineJewelleryShopping.Models.banner

@{
    ViewBag.Title = "Details";
}
@{

    ViewBag.PageHeading = "Detail Banner";
}
<div id="table-content">
    <table width="100%" id="table-form">
        <tr align="left">
            <th width="100px">Url</th>
            <td>@Html.DisplayFor(model => model.banner_url)</td>
        </tr>
        <tr align="left">
            <th>Image</th>
            <td><img src="@Url.Content(Model.banner_image)" alt="" style="max-width:930px;"/></td>
        </tr>
        <tr><th colspan="2">@Html.ActionLink("Edit", "Edit", new { id = Model.banner_id }) |
        @Html.ActionLink("Back to List", "Index")</th></tr>
    </table>
</div>

src/OnlineJewelleryShopping/Areas/Admin/Views/Banner/Edit.cshtml
@model OnlineJewelleryShopping.Areas.Admin.Models.BannerModel

@{
    ViewBag.Title = "Edit";
}
@{

    ViewBag.PageHeading = "Edit Banner";
}
<div id="table-content">
@using (Html.BeginForm("Edit", "Banner", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <table width="100%" id="table-form">
        <tr align="left">
            @Html.HiddenFor(m => m.banner_id)
            <th width="100px">Url</th>
            <td>@Html.TextBoxFor(m => m.banner_url, new { id = "banner_url" }) @Html.ValidationMessageFor(m => m.banner_url)</td>
        </tr>
        <tr>
            <th width="100px" align="left" valign="top">Image</th>
            <td>
                @Html.TextBoxFor(m => m.banner_image, new { id = "banner_image", @readonly = "readonly" })
                <input type="button" name="name" value="Browse Server" onclick="BrowseServerFileAndSetImage('banner_image', 'imgPreview');" />
                @Html.ValidationMessageFor(m => m.banner_image)
                <br />
                <img src="@Url.Content(Model.banner_image)" alt="" style="max-width:930px;" id="imgPreview" />
            </td>
        </tr>
        <tr><th colspan="2"><input type="submit" value="Save" /> @Html.ActionLink("Back to List", "Index")</th></tr>
    </table>
}
</div>

src/OnlineJewelleryShopping/Areas/Admin/Views/Banner/Index.cshtml
@model PagedList.IPagedList<OnlineJewelleryShopping.Models.banner>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
}
@{

    ViewBag.PageHeading = "List Banner";
}

<p>
    @Html.ActionLink("Create New", "Create") 
</p>
<br />
<br />
<form id="mainform" method="post">
    <div id="table-content">
        <table border="0" width="100%" cellpadding="0" cellspacing="0" id="product-table">
            <tr>
                <th class="table-header-check" ><a id="toggle-all"></a></th>
                <th class="table-header-repeat line-left"><a href="">Url</a></th>
                <th class="table-header-repeat line-left" width="510px"><a href="">Image</a></th>
                <th class="table-header-options line-left" width="100px"><a href="">Options</a></th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td valign="top">
                        <input type="checkbox" name="@item.banner_id" />
                    </td>
                    <td valign="top">
                        @Html.DisplayFor(modelItem => item.banner_url)
                    </td>
                    <td>
                        <img src="@Url.Content(item.banner_image)" style="max-width:400px;" />
                    </td>
                    <td valign="top">
                        @Html.ActionLink("Edit", "Edit", new { id = item.banner_id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.banner_id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.banner_id })
                    </td>
                </tr>
            }
        </table>
    </div>
    <div id="actions-box"><input type="submit" value="Delete" onclick="javascript: return confirm('Are you sure to delete ?');" /></div>
</form>
<table border="0" cellpadding="0" cellspacing="0" id="paging-table">
    <tr>
        <td>
            <a href="/Admin/Banner/Index?PageNumber=1" class="page-far-left"></a>
            <a href="/Admin/Banner/Index?PageNumber=@Html.Raw((Model.PageNumber == 1 ? 1 : Model.PageNumber - 1).ToString())" class="page-left"></a>
            <div id="page-info">Page <strong>@Model.PageNumber</strong> / @Model.PageCount</div>
            <a href="/Admin/Banner/Index?PageNumber=@Html.Raw((Model.PageNumber == Model.PageCount ? Model.PageCount : Model.PageNumber + 1).ToString())" class="page-right"></a>
            <a href="/Admin/Banner/Index?PageNumber=@Model.PageCount" class="page-far-right"></a>
            <input type="number" name="PageNumber" value="" max="@Model.PageCount" min="1" style="width:50px;" onkeypress="CatchEnterKeyPress(event, this);" />
        </td>
    </tr>
</table>

<div class="clear"></div>
@section Scripts{
    <script>
        function CatchEnterKeyPress(e, textarea) {
            var code = (e.keyCode ? e.keyCode : e.which);
            if (code == 13) { //Enter keycode
                if (textarea.value == "" || parseInt(textarea.value) > parseInt(@Model.PageCount.ToString())) {
                    alert('Please enter a number in the range of total page.Max page number is @Model.PageCount .');
                } else {
                    location.href = "/Admin/Banner/Index?SortOrder=@ViewBag.CurrentSort&SearchName=@ViewBag.SearchName&PageNumber=" + textarea.value;
                }
            }
        }
    </script>
}