src/OnlineJewelleryShopping/Models/term_and_conditional.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineJewelleryShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class term_and_conditional
    {
        public int term_and_conditional_id { get; set; }
        public string term_and_conditional_conten { get; set; }
    }
}

src/OnlineJewelleryShopping/Areas/Admin/Controllers/TermAndConditionalController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineJewelleryShopping.Models;

namespace OnlineJewelleryShopping.Areas.Admin.Controllers
{
    public class TermAndConditionalController : Controller
    {
        private OnlineJewelleryStoreEntities db = new OnlineJewelleryStoreEntities();

        //
        // GET: /Admin/TermAndConditional/

        public ActionResult Index()
        {
            var obj = db.term_and_conditional.FirstOrDefault();
            if (obj != null)
            {
                return View(obj);

            }
            obj = new term_and_conditional(){term_and_conditional_conten = "No data"};
            db.term_and_conditional.Add(obj);
            db.SaveChanges();
            return View(obj);
        }

       

        
        
        //
        // GET: /Admin/TermAndConditional/Edit/5
        
        public ActionResult Edit()
        {
            term_and_conditional term_and_conditional = db.term_and_conditional.FirstOrDefault();
            if (term_and_conditional == null)
            {
                term_and_conditional = new term_and_conditional() {  term_and_conditional_conten = "No data"};
                db.term_and_conditional.Add(term_and_conditional);
                db.SaveChanges();
                return View(term_and_conditional);
            }
            return View(term_and_conditional);
        }

        //
        // POST: /Admin/TermAndConditional/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(term_and_conditional term_and_conditional)
        {
            var obj = db.term_and_conditional.FirstOrDefault();
            if (obj != null)
            {
                obj.term_and_conditional_conten = term_and_conditional.term_and_conditional_conten;
                db.SaveChanges();
                return RedirectToAction("Index");

            }
            obj = new term_and_conditional() { term_and_conditional_conten = term_and_conditional.term_and_conditional_conten };
            db.term_and_conditional.Add(obj);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

src/OnlineJewelleryShopping/Areas/Admin/Views/TermAndConditional/Edit.cshtml
@model OnlineJewelleryShopping.Models.term_and_conditional

@{
    ViewBag.Title = "Edit Term and conditional infomation";
}
@{
    ViewBag.PageHeading = "Edit Term and conditional infomation";

}
@using (Html.BeginForm("Edit", "TermAndConditional", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.TextAreaFor(model => model.term_and_conditional_conten, new { @class = "ckeditor" })
    <br />
    <br />
    <div class="clear"></div>
    <p align="center" style="font-weight:bold;">
        <input type="submit" value="Save" />@Html.ActionLink("Back to view content", "Index")
    </p>
}

src/OnlineJewelleryShopping/Areas/Admin/Views/TermAndConditional/Index.cshtml
@model OnlineJewelleryShopping.Models.term_and_conditional

@{
    ViewBag.Title = "Term and Conditional Infomation";
}
@{
    ViewBag.PageHeading = "Term and Conditional Infomation";
}


<div id="table-content">
    @if (Model != null && Model.term_and_conditional_conten != null)
    {
        @Html.Raw(Model.term_and_conditional_conten)
    }
    else
    {
        <p>No data</p>
    }

</div>
<p align="center" style="font-weight:bold;">
    @Html.ActionLink("Edit Content", "Edit", "TermAndConditional", new { area = "Admin" }, new { @class = "btn" })
</p>